[workspace]
authors = ["Vorschreibung <vorschreibung@gmail.com>"]
channels = ["conda-forge"]
name = "omni-bot"
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]
"dev" = { cmd = ["python", "./dev.py"] }

[dependencies]
"meson" = "1.12.1.*"
"zig" = "0.16.0.*"
