[binaries]
c = ['zig', 'cc']
cpp = ['zig', 'c++']
ar = ['zig', 'ar']
strip = ['zig', 'strip']

[properties]
# Cross-compiled modules cannot run during configuration.
needs_exe_wrapper = true

[built-in options]
c_args = ['--target=x86_64-macos-none', '-DPHYSFS_FORCE_UNIX']
c_link_args = ['--target=x86_64-macos-none']
cpp_args = ['--target=x86_64-macos-none', '-stdlib=libc++']
cpp_link_args = ['--target=x86_64-macos-none', '-stdlib=libc++']

[host_machine]
system = 'darwin'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'
