#!/usr/bin/env python3
"""Run Zig's C driver while normalizing Boost.Build's x86 target name."""

import os
import sys


def main() -> None:
    """Replace Clang's i386 spelling with the equivalent Zig target."""
    driver = os.environ["ZIG_CC"]
    arguments = [
        "--target=x86-linux-gnu" if argument == "--target=i386-pc-linux" else argument
        for argument in sys.argv[1:]
    ]
    os.execv(driver, [driver, *arguments])


if __name__ == "__main__":
    main()
